using System.ComponentModel.DataAnnotations;

namespace MobileStore.Models
{
    public class Mobile
{
    public int Id { get; set; } // Auto-generated by MySQL
    public required string Name { get; set; }
    public required string Brand { get; set; }
    public decimal Price { get; set; }
    public int Stock { get; set; }
}
    
}
